
const API=(window.API_BASE_URL||"").replace(/\/$/,"");\nlet csrf="",role="staff";const $=x=>document.getElementById(x);const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url,method="GET",body){let o={method,headers:{}};if(body!==undefined){o.headers={"Content-Type":"application/json","X-CSRF-Token":csrf};o.body=JSON.stringify(body)}let r=await fetch(API+url,{...o,credentials:"include"}),d=await r.json().catch(()=>({}));if(r.status===401){location.href="./login.html";throw Error("Login required")}if(!r.ok)throw Error(d.error||"Request failed");return d}
function data(f){return Object.fromEntries(new FormData(f))}
async function init(){let r=await fetch(API+"/api/me",{credentials:"include"});if(!r.ok){location.href="./login.html";return}let me=await r.json();csrf=me.csrf;role=me.role;if(role!=="admin")$("users").style.display="none";await load();setInterval(()=>load().catch(()=>{}),15000)}
async function load(){let [s,m,r,l]=await Promise.all([api("/api/summary"),api("/api/mappings"),api("/api/replies"),api("/api/logs")]);$("nBots").textContent=s.bots.filter(x=>x.status==="running").length+"/"+s.bots.length;$("nMaps").textContent=s.maps;$("nReplies").textContent=s.replies;$("nLogs").textContent=s.logs;
$("botList").innerHTML=s.bots.map(b=>`<div><b>${esc(b.name)}</b> · ${esc(b.platform)} · ${esc(b.status)} ${esc(b.error)} <button onclick="toggleBot(${b.id})">Bật/Tắt</button> <button onclick="del('bots',${b.id})">Xóa</button></div>`).join("")||"Chưa có bot";
$("mapList").innerHTML=m.map(x=>`<div>Discord ${esc(x.discord_id)} ↔ Telegram ${esc(x.telegram_id)} <button onclick="toggle('mappings',${x.id})">ON/OFF</button> <button onclick="del('mappings',${x.id})">Xóa</button></div>`).join("");
$("replyList").innerHTML=r.map(x=>`<div><b>${esc(x.trigger)}</b> · ${esc(x.platform)}<br>${esc(x.response)} <button onclick="toggle('replies',${x.id})">ON/OFF</button> <button onclick="del('replies',${x.id})">Xóa</button></div>`).join("");
$("logList").innerHTML=l.map(x=>`<div><b>${esc(x.level)} · ${esc(x.event)}</b> (${esc(x.platform)})<br>${esc(x.details)}<br><small>${esc(x.created_at)}</small></div>`).join("");
if(role==="admin"){$("userList").innerHTML=(await api("/api/users")).map(u=>`<div>${esc(u.username)} · ${esc(u.role)} · ${u.active?"Active":"Disabled"} <button onclick="toggleUser(${u.id})">Khóa/Mở</button></div>`).join("")}}
async function bind(id,url){$(id).onsubmit=async e=>{e.preventDefault();try{await api(url,"POST",data(e.target));e.target.reset();await load()}catch(x){alert(x.message)}}}
bind("botForm","/api/bots");bind("mapForm","/api/mappings");bind("replyForm","/api/replies");bind("userForm","/api/users");
async function toggleBot(id){try{await api(`/api/bots/${id}/toggle`,"POST",{});await load()}catch(e){alert(e.message)}}
async function toggle(t,id){await api(`/api/${t}/${id}/toggle`,"POST",{});load()}async function del(t,id){if(confirm("Xóa mục này?")){await api(`/api/${t}/${id}`,"DELETE");load()}}async function toggleUser(id){await api(`/api/users/${id}/toggle`,"POST",{});load()}
async function backup(which){let r=await fetch(API+(which==="logs"?"/api/backup/logs":"/api/backup"),{method:"POST",headers:{"X-CSRF-Token":csrf},credentials:"include"});if(!r.ok){alert("Backup thất bại");return}let a=document.createElement("a"),u=URL.createObjectURL(await r.blob());a.href=u;a.download=which+".sqlite";a.click();URL.revokeObjectURL(u)}
async function logout(){await api("/api/logout","POST",{});location.href="./login.html"}init();
